# Generated by Django 5.0.2 on 2024-02-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Description'),
        ),
    ]
