# Generated by Django 5.0.2 on 2024-02-21 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substack', '0002_source_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubstackRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='Started', max_length=1000, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
