# Generated by Django 5.0.2 on 2024-02-21 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substack', '0003_substackrun_source_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=280, unique=True)),
                ('tag', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=280, verbose_name='Name')),
                ('surname', models.CharField(default='', max_length=280, verbose_name='Surame')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(allow_unicode=True, editable=False, max_length=280, unique=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='author_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name', 'surname'],
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=1000, null=True)),
                ('link', models.CharField(max_length=1000, unique=True)),
                ('image_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('published', models.DateTimeField(blank=True, null=True)),
                ('story_type', models.CharField(blank=True, choices=[('1', 'Article'), ('2', 'Video'), ('3', 'Podcast')], default='1', max_length=200, null=True)),
                ('slug', models.SlugField(allow_unicode=True, max_length=280, unique=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_author', to='substack.author')),
                ('dislikes', models.ManyToManyField(blank=True, related_name='story_dislikes', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='story_likes', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, related_name='news_tags', to='substack.storytag')),
            ],
            options={
                'ordering': ['-published'],
            },
        ),
    ]
