# Generated by Django 5.0.2 on 2024-02-21 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substack', '0004_storytag_author_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='story_source', to='substack.source'),
        ),
    ]
