# Generated by Django 5.0.2 on 2024-02-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substack', '0006_story_bookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='content',
            field=models.TextField(blank=True, default='', max_length=100000, null=True, verbose_name='Content'),
        ),
    ]
